### ISSUE TITLE
There is no way to listen to web push subscription change.

### ISSUE THREAD

**Issue by anandrmedia** [Engagespot/engagespot#18]
# 🐛 bug report

## Preflight Checklist

- [x ] I have read the [Contributing Guidelines][contributing] for this project.
- [x ] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Browsers often expire the web push subscriptions and generate new subscription credentials. We don't track this, so we'll lose active web push subscriptions of our users after some time and they won't be able to receive push notifications at all.

## How has this issue affected you? What are you trying to accomplish?
Some users are not able to receive web push notifications after several days or weeks because their subscription changed.

### Your Environment

[code_of_conduct]: https://github.com/Engagespot/engagespot/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/Engagespot/engagespot/blob/master/CONTRIBUTING.md

**Comment by hemandev** [comment]
This has been fixed on [v1.1.6](https://github.com/Engagespot/engagespot/blob/master/packages/react-component/CHANGELOG.md#116)
