### ISSUE TITLE
unread count in title (1) stays even after reading all notifications

### ISSUE THREAD

**Issue by anandrmedia** [Engagespot/engagespot#20]
# 🐛 bug report

## Preflight Checklist

- [ x] I have read the [Contributing Guidelines][contributing] for this project.
- [ x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [ x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
browser title count (1) stays even after reading all notification

### Your Environment

[code_of_conduct]: https://github.com/Engagespot/engagespot/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/Engagespot/engagespot/blob/master/CONTRIBUTING.md

**Comment by hemandev** [comment]
Fixed in React component v1.1.8
